version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u171-jdk # the primary container, where your job's commands are run

    working_directory: ~/circle-ci-attempts
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

  deploy:
   docker:
     - image: circleci/buildpack-deps:trusty
      steps:
     - checkout
     - run:
         name: Deploy app on heroku
         command: |
           git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      -build
      -deploy:
        requires:
          -build

#version: 2.1
#
#orbs:
#  maven: circleci/maven@0.0.12
#
#workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
#
#  deploy:
#
